token: ''
maxShards: 1
commandPrefix: 'pp!'
commandsCaseSensitive: false
presence:
  updateInterval: 60
  activities:
    - type: 'DEFAULT'
      text: 'Text 1'
    - type: 'WATCHING'
      text: 'Text 2'
    - type: 'LISTENING'
      text: 'Text 3'
